apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bayport-services
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: git@github.com:NovataInc/novata-k8s-manifests.git
        revision: master
        directories:
          - path: application-charts/*/values/*
