apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: za-cluster-appsets
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: 'https://github.com/kanzifucius/muti-cluster-gitops-template'
    path: clusters/za
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
